### PR TITLE
Fix cannot find module 'versor/src/index'

### PR DESCRIPTION
**Pull request by antoine-le-calloch**
Fixes the error `Cannot find module 'versor/src/index'` on `versor 0.2.0` by updating the import to:
```
import versor from 'versor';
```

Even though the code was originally targeting `versor: ~0.1.2`, this change also ensures compatibility with `versor: 0.2.0` by handling its stricter exports field.

### CODE REVIEW

**Comment by antoine-le-calloch** [comment]
Hello @vasturiano, I found an issue with the versor import starting from version 1.5.5.  
With versor 0.2.0, the import cannot be resolved anymore due to stricter exports.

**Comment by vasturiano** [comment]
@antoine-le-calloch thanks for reaching out.

This change won't work with `versor` version `0.1.2`. Because that's prior to this fix being applied, that was referencing a non-existent file:
https://github.com/d3/versor/commit/7fb65a1b4d091b813ca56877a88c639363f3b6e4

So, at the very least in this PR we need to bump the package dependency to `"versor": "^0.2"`.

But there is something I'm missing, how did you force `d3-geo-json` to consume from `0.2.0` when it currently has 
https://github.com/vasturiano/d3-geo-zoom/blob/f1c03c54166595156389f92a1d22b57fc2548d53/package.json#L46

Additionally, the `src/index.js` file is the exact same mentioned in the latest version of `versor` exports and also in this code, so the outcome should be the same. How are you getting this error? Are you able to reproduce it in a https://codesandbox.io/ ?
